// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg3zmf7bt862lxw0OvA02Vp3JctuG5FdA',
    appId: '1:72364372545:android:d650a7edd7a8990a1a8cc0',
    messagingSenderId: '72364372545',
    projectId: 'evently-islam-project',
    storageBucket: 'evently-islam-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZ_JGxQXYZiPYu6naElGwHG-tjnOGvQs',
    appId: '1:72364372545:ios:2a10f034df8244901a8cc0',
    messagingSenderId: '72364372545',
    projectId: 'evently-islam-project',
    storageBucket: 'evently-islam-project.firebasestorage.app',
    androidClientId: '72364372545-j80uc03ouv6baqvndqgcdh9o1lsh5t8r.apps.googleusercontent.com',
    iosClientId: '72364372545-5or5aqb522dhbsv5hmcn6vl9ufoiel95.apps.googleusercontent.com',
    iosBundleId: 'com.example.evenrly',
  );

}